version: "3.8"

services:
  fiber-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber-server
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - emqx
    networks:
      - chacha_net
    command: ["sh", "-c", "/wait-for-it.sh emqx:8883 ./server"]
    volumes:
      - /root/chacha-jarvis/emqx/certs:/certs   # ✅ 절대경로 사용
      - /root/chacha-jarvis/backend/go_fiber_server/wait-for-it.sh:/wait-for-it.sh # emqx 기다리기

networks:
  chacha_net:
    external: true
