version: "3.8"

services:
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    networks:
      - chacha_net

networks:
  chacha_net:
    external: true
