-- DROP SCHEMA administrative;

CREATE SCHEMA administrative AUTHORIZATION meta;

-- administrative.administrative_boundaries_by_province definition

-- Drop table

-- DROP TABLE administrative.administrative_boundaries_by_province;

CREATE TABLE administrative.administrative_boundaries_by_province (
	province_code text NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(multipolygon, 4326) NOT NULL,
	osm_id int8 NOT NULL,
	"name" text NULL,
	name_en text NULL,
	boundary text NULL,
	admin_level int4 NULL,
	country_code bpchar(2) NOT NULL,
	admin_centre_node_id int8 NULL,
	admin_centre_node_lat float8 NULL,
	admin_centre_node_lng float8 NULL,
	label_node_id int8 NULL,
	label_node_lat float8 NULL,
	label_node_lng float8 NULL,
	district_code text NULL,
	CONSTRAINT administrative_boundaries_by_province_pkey PRIMARY KEY (province_code, id),
	CONSTRAINT administrative_boundaries_by_province_unique UNIQUE (province_code, osm_id)
)
PARTITION BY LIST (province_code);
CREATE INDEX abp_province_district_idx ON ONLY administrative.administrative_boundaries_by_province USING btree (province_code, district_code);


-- administrative.administrative_boundaries_by_province foreign keys

ALTER TABLE administrative.administrative_boundaries_by_province ADD CONSTRAINT administrative_boundaries_by_province_district_fk FOREIGN KEY (province_code,district_code) REFERENCES administrative.administrative_districts(province_code,district_code) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE administrative.administrative_boundaries_by_province ADD CONSTRAINT administrative_boundaries_by_province_level_fk FOREIGN KEY (admin_level) REFERENCES administrative.administrative_level_mapping(osm_admin_level);
ALTER TABLE administrative.administrative_boundaries_by_province ADD CONSTRAINT administrative_boundaries_by_province_province_fk FOREIGN KEY (province_code) REFERENCES administrative.administrative_provinces(province_code);


-- administrative.administrative_boundary_centers_by_province definition

-- Drop table

-- DROP TABLE administrative.administrative_boundary_centers_by_province;

CREATE TABLE administrative.administrative_boundary_centers_by_province (
	province_code text NOT NULL,
	osm_id int8 NOT NULL,
	longitude float8 NOT NULL,
	latitude float8 NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	district_code text NULL,
	CONSTRAINT administrative_boundary_centers_by_province_pkey PRIMARY KEY (province_code, osm_id)
);
CREATE INDEX abp_centers_province_district_idx ON administrative.administrative_boundary_centers_by_province USING btree (province_code, district_code);
CREATE INDEX administrative_boundary_centers_by_province_cc_idx ON administrative.administrative_boundary_centers_by_province USING btree (province_code);
CREATE INDEX administrative_boundary_centers_by_province_osm_idx ON administrative.administrative_boundary_centers_by_province USING btree (osm_id);


-- administrative.administrative_boundary_centers_by_province foreign keys

ALTER TABLE administrative.administrative_boundary_centers_by_province ADD CONSTRAINT administrative_boundary_centers_by_province_district_fk FOREIGN KEY (province_code,district_code) REFERENCES administrative.administrative_districts(province_code,district_code) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE administrative.administrative_boundary_centers_by_province ADD CONSTRAINT administrative_boundary_centers_by_province_fk FOREIGN KEY (province_code,osm_id) REFERENCES administrative.administrative_boundaries_by_province(province_code,osm_id) ON DELETE CASCADE;


-- administrative.administrative_countries definition

-- Drop table

-- DROP TABLE administrative.administrative_countries;

CREATE TABLE administrative.administrative_countries (
	country_code bpchar(2) NOT NULL,
	country_name text NOT NULL,
	CONSTRAINT countries_pkey PRIMARY KEY (country_code)
);

-- administrative.administrative_district_centers definition

-- Drop table

-- DROP TABLE administrative.administrative_district_centers;

CREATE TABLE administrative.administrative_district_centers (
	province_code text NOT NULL,
	district_code text NOT NULL,
	longitude float8 NOT NULL,
	latitude float8 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT administrative_district_centers_lonlat_chk CHECK ((((longitude >= ('-180'::integer)::double precision) AND (longitude <= (180)::double precision)) AND ((latitude >= ('-90'::integer)::double precision) AND (latitude <= (90)::double precision)))),
	CONSTRAINT administrative_district_centers_pkey PRIMARY KEY (province_code, district_code)
);
CREATE INDEX administrative_district_centers_province_idx ON administrative.administrative_district_centers USING btree (province_code);


-- administrative.administrative_district_centers foreign keys

ALTER TABLE administrative.administrative_district_centers ADD CONSTRAINT administrative_district_centers_fk FOREIGN KEY (province_code,district_code) REFERENCES administrative.administrative_districts(province_code,district_code) ON DELETE CASCADE ON UPDATE CASCADE;




-- administrative.administrative_districts definition

-- Drop table

-- DROP TABLE administrative.administrative_districts;

CREATE TABLE administrative.administrative_districts (
	province_code text NOT NULL,
	province_name text NOT NULL,
	country_code bpchar(2) NOT NULL,
	district_code text NOT NULL,
	geom public.geometry(multipolygon, 4326) NULL,
	osm_id int8 NULL,
	"name" text NULL,
	name_en text NULL,
	boundary text NULL,
	admin_level int4 NULL,
	admin_centre_node_id int8 NULL,
	admin_centre_node_lat float8 NULL,
	admin_centre_node_lng float8 NULL,
	label_node_id int8 NULL,
	label_node_lat float8 NULL,
	label_node_lng float8 NULL,
	CONSTRAINT administrative_districts_pk PRIMARY KEY (province_code, district_code)
);
CREATE INDEX administrative_districts_gix ON administrative.administrative_districts USING gist (geom);
CREATE INDEX administrative_districts_osm_id_idx ON administrative.administrative_districts USING btree (osm_id);
CREATE INDEX administrative_districts_province_idx ON administrative.administrative_districts USING btree (province_code);


-- administrative.administrative_level_mapping definition

-- Drop table

-- DROP TABLE administrative.administrative_level_mapping;

CREATE TABLE administrative.administrative_level_mapping (
	osm_admin_level int4 NOT NULL,
	iso_un_level_code varchar(10) NULL,
	iso_un_level_int int4 NULL,
	description_ko varchar(100) NULL,
	description_en varchar(100) NULL,
	CONSTRAINT administrative_level_mapping_pkey PRIMARY KEY (osm_admin_level)
);


-- administrative.administrative_provinces definition

-- Drop table

-- DROP TABLE administrative.administrative_provinces;

CREATE TABLE administrative.administrative_provinces (
	province_code text NOT NULL,
	province_name text NOT NULL,
	country_code bpchar(2) NOT NULL,
	CONSTRAINT administrative_provinces_pkey PRIMARY KEY (province_code)
);


-- administrative.administrative_provinces foreign keys

ALTER TABLE administrative.administrative_provinces ADD CONSTRAINT administrative_provinces_country_code_fkey FOREIGN KEY (country_code) REFERENCES administrative.administrative_countries(country_code);