
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;



-- 0) 기본 스키마 (선택)
CREATE SCHEMA IF NOT EXISTS administrative;

CREATE TABLE administrative.administrative_countries (
	country_code bpchar(2) NOT NULL,
	country_name text NOT NULL,
	CONSTRAINT countries_pkey PRIMARY KEY (country_code)
);

COMMENT ON TABLE  administrative.administrative_countries IS '국가 코드와 이름 매핑 테이블';
COMMENT ON COLUMN administrative.administrative_countries.country_code IS 'ISO 3166-1 alpha-2 국가 코드';
COMMENT ON COLUMN administrative.administrative_countries.country_name IS '국가 이름';




CREATE TABLE IF NOT EXISTS administrative.administrative_provinces (
  province_code TEXT PRIMARY KEY,                 -- 예: 'KR-SEOUL', 'KR-INCHEON'
  province_name TEXT NOT NULL,                    -- 예: '서울특별시', '인천광역시'
  country_code  CHAR(2) NOT NULL
    REFERENCES administrative.administrative_countries(country_code)
);

COMMENT ON TABLE  administrative.administrative_provinces IS '광역시·도(최상위 지방정부) 식별 코드 및 이름';
COMMENT ON COLUMN administrative.administrative_provinces.province_code IS '광역시·도 식별 코드';
COMMENT ON COLUMN administrative.administrative_provinces.province_name IS '광역시·도 이름';
COMMENT ON COLUMN administrative.administrative_provinces.country_code  IS '소속 국가 코드';





CREATE TABLE IF NOT EXISTS administrative.administrative_level_mapping (
  osm_admin_level   INT PRIMARY KEY,
  iso_un_level_code VARCHAR(10),
  iso_un_level_int  INT,
  description_ko    VARCHAR(100),
  description_en    VARCHAR(100)
);

COMMENT ON TABLE  administrative.administrative_level_mapping IS 'OSM admin_level ↔ 내부 표준 레벨 매핑(한국 기준)';
COMMENT ON COLUMN administrative.administrative_level_mapping.osm_admin_level   IS 'OSM admin_level(정수)';
COMMENT ON COLUMN administrative.administrative_level_mapping.iso_un_level_code IS '내부 표준 레벨 코드(문자)';
COMMENT ON COLUMN administrative.administrative_level_mapping.iso_un_level_int  IS '내부 표준 레벨 코드(숫자)';
COMMENT ON COLUMN administrative.administrative_level_mapping.description_ko    IS '설명(한국어)';
COMMENT ON COLUMN administrative.administrative_level_mapping.description_en    IS '설명(영어)';



CREATE table IF NOT EXISTS  administrative.administrative_boundaries_by_province (
	province_code text NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(multipolygon, 4326) NOT NULL,
	osm_id int8 NOT NULL,
	"name" text NULL,
	name_en text NULL,
	boundary text NULL,
	admin_level int4 NULL,
	country_code bpchar(2) NOT NULL,
	admin_centre_node_id int8 NULL,
	admin_centre_node_lat float8 NULL,
	admin_centre_node_lng float8 NULL,
	label_node_id int8 NULL,
	label_node_lat float8 NULL,
	label_node_lng float8 NULL,
	CONSTRAINT administrative_boundaries_by_province_pkey PRIMARY KEY (province_code, id),
	CONSTRAINT administrative_boundaries_by_province_unique UNIQUE (province_code, osm_id),
	CONSTRAINT administrative_boundaries_by_province_level_fk FOREIGN KEY (admin_level) REFERENCES administrative.administrative_level_mapping(osm_admin_level),
	CONSTRAINT administrative_boundaries_by_province_province_fk FOREIGN KEY (province_code) REFERENCES administrative.administrative_provinces(province_code)
)
PARTITION BY LIST (province_code);


COMMENT ON TABLE  administrative.administrative_boundaries_by_province IS
'광역시·도 단위 LIST 파티셔닝된 OSM 행정경계(멀티폴리곤, EPSG:4326).';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.province_code IS '파티션 키: 광역시·도 식별 코드';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.geom          IS '행정경계 멀티폴리곤(4326)';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.osm_id        IS 'OpenStreetMap 원본 ID';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.name          IS '행정경계 이름(현지어)';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.name_en       IS '행정경계 이름(영문)';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.boundary      IS 'OSM boundary 태그 값';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.admin_level   IS 'OSM admin_level 값';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.country_code  IS '소속 국가 코드';


COMMENT ON COLUMN administrative.administrative_boundaries_by_province.admin_centre_node_id  IS '행정센터 OSM node ID';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.admin_centre_node_lat IS '행정센터 위도';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.admin_centre_node_lng IS '행정센터 경도';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.label_node_id         IS '라벨용 OSM node ID';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.label_node_lat        IS '라벨 표시 위도';
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.label_node_lng        IS '라벨 표시 경도';









-- 서울특별시
CREATE TABLE IF NOT EXISTS administrative.administrative_boundaries_by_province_kr_seoul
  PARTITION OF administrative.administrative_boundaries_by_province
  FOR VALUES IN ('KR-SEOUL');

-- 인천광역시
CREATE TABLE IF NOT EXISTS administrative.administrative_boundaries_by_province_kr_incheon
  PARTITION OF administrative.administrative_boundaries_by_province
  FOR VALUES IN ('KR-INCHEON');



-- 파티션별 인덱스(공간, 이름, 레벨)
CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_seoul_geom_gix
  ON administrative.administrative_boundaries_by_province_kr_seoul USING GIST (geom);
CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_seoul_name_idx
  ON administrative.administrative_boundaries_by_province_kr_seoul (name);
CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_seoul_level_idx
  ON administrative.administrative_boundaries_by_province_kr_seoul (admin_level);

CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_incheon_geom_gix
  ON administrative.administrative_boundaries_by_province_kr_incheon USING GIST (geom);
CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_incheon_name_idx
  ON administrative.administrative_boundaries_by_province_kr_incheon (name);
CREATE INDEX IF NOT EXISTS administrative_boundaries_by_province_kr_incheon_level_idx
  ON administrative.administrative_boundaries_by_province_kr_incheon (admin_level);















-- ==========================================================
-- 0) administrative_districts 테이블: 전체 컬럼 보유하도록 재구성
--    (없으면 생성, 있으면 ALTER로 컬럼 보강)
-- ==========================================================
CREATE TABLE IF NOT EXISTS administrative.administrative_districts (
  -- 기본 키: (province_code, district_code)
  province_code              text            NOT NULL,
  province_name              text            NOT NULL,
  country_code               char(2)         NOT NULL,
  district_code              text            NOT NULL,  -- 예: junggu, seochogu

  -- OSM 원본 필드 + 지오메트리
  geom                       geometry(MultiPolygon, 4326),
  osm_id                     bigint,
  name                       text,
  name_en                    text,
  boundary                   text,
  admin_level                integer,
  admin_centre_node_id       bigint,
  admin_centre_node_lat      double precision,
  admin_centre_node_lng      double precision,
  label_node_id              bigint,
  label_node_lat             double precision,
  label_node_lng             double precision,

  CONSTRAINT administrative_districts_pk PRIMARY KEY (province_code, district_code)
);



-- 공간/조회 인덱스
CREATE INDEX IF NOT EXISTS administrative_districts_gix
  ON administrative.administrative_districts USING GIST (geom);
CREATE INDEX IF NOT EXISTS administrative_districts_province_idx
  ON administrative.administrative_districts (province_code);
CREATE INDEX IF NOT EXISTS administrative_districts_osm_id_idx
  ON administrative.administrative_districts (osm_id);


-- ==========================================================
-- administrative.administrative_districts 테이블/컬럼 주석
-- ==========================================================
COMMENT ON TABLE administrative.administrative_districts
  IS '광역시·도에 속한 구(區) 엔터티. OSM 원본 속성(geom 등)까지 포함. district_code는 영문 슬러그(예: junggu, seochogu)이며 province_code 내에서 유일하다.';

COMMENT ON COLUMN administrative.administrative_districts.province_code
  IS '광역시·도 코드 (예: KR-INCHEON, KR-SEOUL). ISO 3166-2 기준을 권장.';
COMMENT ON COLUMN administrative.administrative_districts.province_name
  IS '광역시·도 명(한글) (예: 인천광역시, 서울특별시).';
COMMENT ON COLUMN administrative.administrative_districts.country_code
  IS '국가 코드 (예: KR). ISO 3166-1 alpha-2.';
COMMENT ON COLUMN administrative.administrative_districts.district_code
  IS '구 코드(영문 슬러그). name_en(없으면 name)에서 영문/숫자만 남겨 생성(예: Jung-gu → junggu). 같은 province_code 내 유일.';

COMMENT ON COLUMN administrative.administrative_districts.geom
  IS '구 경계 도형 (MultiPolygon, EPSG:4326). 적재 시 ST_MakeValid 및 ST_Multi로 정규화.';
COMMENT ON COLUMN administrative.administrative_districts.osm_id
  IS 'OSM 개체 식별자(주로 relation/way ID). 원본 추적 및 중복 방지용.';
COMMENT ON COLUMN administrative.administrative_districts.name
  IS '구 명(로컬 표기).';
COMMENT ON COLUMN administrative.administrative_districts.name_en
  IS '구 명(영문 표기).';
COMMENT ON COLUMN administrative.administrative_districts.boundary
  IS 'OSM boundary 태그 값 (예: administrative).';
COMMENT ON COLUMN administrative.administrative_districts.admin_level
  IS 'OSM admin_level. 일반적으로 구(자치구)는 6을 사용.';
COMMENT ON COLUMN administrative.administrative_districts.admin_centre_node_id
  IS '행정중심(청사 등) OSM 노드 ID.';
COMMENT ON COLUMN administrative.administrative_districts.admin_centre_node_lat
  IS '행정중심 위도(WGS84).';
COMMENT ON COLUMN administrative.administrative_districts.admin_centre_node_lng
  IS '행정중심 경도(WGS84).';
COMMENT ON COLUMN administrative.administrative_districts.label_node_id
  IS '레이블 배치를 위한 기준 OSM 노드 ID.';
COMMENT ON COLUMN administrative.administrative_districts.label_node_lat
  IS '레이블 기준 위도(WGS84).';
COMMENT ON COLUMN administrative.administrative_districts.label_node_lng
  IS '레이블 기준 경도(WGS84).';





  
  
  
CREATE TABLE administrative.administrative_boundary_centers_by_province (
	province_code text NOT NULL,
	osm_id int8 NOT NULL,
	longitude float8 NOT NULL,
	latitude float8 NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	district_code text NULL,
	CONSTRAINT administrative_boundary_centers_by_province_pkey PRIMARY KEY (province_code, osm_id),
	CONSTRAINT administrative_boundary_centers_by_province_district_fk FOREIGN KEY (province_code,district_code) REFERENCES administrative.administrative_districts(province_code,district_code) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT administrative_boundary_centers_by_province_fk FOREIGN KEY (province_code,osm_id) REFERENCES administrative.administrative_boundaries_by_province(province_code,osm_id) ON DELETE CASCADE
);

CREATE INDEX abp_centers_province_district_idx ON administrative.administrative_boundary_centers_by_province USING btree (province_code, district_code);
CREATE INDEX administrative_boundary_centers_by_province_cc_idx ON administrative.administrative_boundary_centers_by_province USING btree (province_code);
CREATE INDEX administrative_boundary_centers_by_province_osm_idx ON administrative.administrative_boundary_centers_by_province USING btree (osm_id);

COMMENT ON TABLE  administrative.administrative_boundary_centers_by_province IS
'광역시·도 파티션 내 행정경계별 대표 좌표(항상 경계 내부의 점; WGS84).';
COMMENT ON COLUMN administrative.administrative_boundary_centers_by_province.longitude IS '경도(WGS84)';
COMMENT ON COLUMN administrative.administrative_boundary_centers_by_province.latitude  IS '위도(WGS84)';












CREATE INDEX IF NOT EXISTS administrative_boundary_centers_by_province_cc_idx
  ON administrative.administrative_boundary_centers_by_province (province_code);

CREATE INDEX IF NOT EXISTS administrative_boundary_centers_by_province_osm_idx
  ON administrative.administrative_boundary_centers_by_province (osm_id);




  
  
  


-- 1) 컬럼 추가 (모든 파티션에 전파됨)
ALTER TABLE administrative.administrative_boundaries_by_province
  ADD COLUMN IF NOT EXISTS district_code text;

-- 주석
COMMENT ON COLUMN administrative.administrative_boundaries_by_province.district_code
  IS '구 코드 (예: KR-INCHEON-JUNGGU, KR-SEOUL-SEOCHOGU).';

-- 2) FK (선택) : districts 기준으로 정합성 관리 원하면 활성화
--    NULL 허용 컬럼이라 FK가 값 있을 때만 체크됨
ALTER TABLE administrative.administrative_boundaries_by_province
  ADD CONSTRAINT administrative_boundaries_by_province_district_fk
  FOREIGN KEY (province_code, district_code)
  REFERENCES administrative.administrative_districts (province_code, district_code)
  ON UPDATE CASCADE
  ON DELETE SET NULL;

-- 3) 인덱스 (파티션드 인덱스로 생성됨)
CREATE INDEX IF NOT EXISTS abp_province_district_idx
  ON administrative.administrative_boundaries_by_province (province_code, district_code);

-- 4) 기존 데이터 백필
--    현재 인천 파티션 데이터 = 중구, 서울 파티션 데이터 = 서초구 라고 했으니 다음처럼 채움
UPDATE administrative.administrative_boundaries_by_province
SET district_code = 'KR-INCHEON-JUNGGU'
WHERE province_code = 'KR-INCHEON'
  AND (district_code IS NULL OR district_code <> 'KR-INCHEON-JUNGGU');

UPDATE administrative.administrative_boundaries_by_province
SET district_code = 'KR-SEOUL-SEOCHOGU'
WHERE province_code = 'KR-SEOUL'
  AND (district_code IS NULL OR district_code <> 'KR-SEOUL-SEOCHOGU');









    
    -- 구 전용 중심점 테이블
CREATE TABLE IF NOT EXISTS administrative.administrative_district_centers (
  province_code  text        NOT NULL,
  district_code  text        NOT NULL,
  longitude      float8      NOT NULL,
  latitude       float8      NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT administrative_district_centers_pkey
    PRIMARY KEY (province_code, district_code),
  CONSTRAINT administrative_district_centers_fk
    FOREIGN KEY (province_code, district_code)
    REFERENCES administrative.administrative_districts(province_code, district_code)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT administrative_district_centers_lonlat_chk
    CHECK (longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90)
);

-- 조회 최적화(선택) – province 단위로 자주 필터링하면 도움됩니다.
CREATE INDEX IF NOT EXISTS administrative_district_centers_province_idx
  ON administrative.administrative_district_centers (province_code);

    


